sonar.projectKey=vg-ms-civic-dates
sonar.host.url=http://localhost:9000
sonar.token=squ_54704be4342d253e440bf943d46011028e15c720



sonar.sources=src
sonar.java.binaries=target
sonar.sourceEncoding=UTF-8